service_now:
  instance_name: "CHANGE_ME"
  user_name: "CHANGE_ME"
  password: "CHANGE_ME"

workflow:
  incident_group_key_field: "u_correlation_id"
  no_update_states: [6,7,8]
  incident_update_fields: ["u_correlation_id","u_work_notes"]

default_incident:
  assignment_group: "{{.CommonAnnotations.assignment_group}}"
  category: "Failure"
  cmdb_ci: "{{.CommonAnnotations.cmdb_ci}}"
  comments: "Alerts list:\n\n{{ range .Alerts }}[{{ .Status }}] {{.StartsAt}} {{.Labels.alertname}}\n{{.Annotations.description}}\n\n{{ end }}"
  company: "{{.CommonAnnotations.company}}"
  contact_type : "{{.CommonAnnotations.contact_type}}"
  description: "Received alerts from AlertManager at {{.ExternalURL}} (\"{{.Receiver}}\" receiver configuration) with common descriptions:\n\n{{.CommonAnnotations.description}}"
  impact: "2"
  short_description: "Alerts from group: {{ range $key, $val := .GroupLabels}}{{ $key }}:{{ $val }} {{end}}"
  subcategory: "Missing Part"
  urgency: "{{.CommonAnnotations.urgency}}"
  u_category: "application"
  u_business_service: "Server"
  u_assignment_group: "TEMTOOLING"
  u_impact: "3"
  u_urgency: "3"
  # ALWAYS USE INDEX 0 OF ALERTS OTHERWISE YOU WILL GET WRONG RESULTS!!
  u_short_description: "ALERT: {{with index .Alerts 0}}{{.Annotations.message}}{{end}} ({{.CommonLabels.cluster}})"
  u_description: "Alerts list:\n\n{{with index .Alerts 0}}[{{ .Status }}] {{.StartsAt}} {{.Labels.alertname}}\n{{.Annotations.message}}\n\n{{ end }}\n\nView all current alerts at {{.ExternalURL}}"
  u_contact_type: "event_alert"
  u_correlation_display: "api"
  u_function: "Create"
  # u_configuration_item: "ZYUMTYCOPW01"
  u_symptom: "Error"
  u_state: "1"
  u_caller: "my_id"